# Generated by Django 4.0.3 on 2022-04-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Команда')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Команды',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('fromCountry', models.CharField(max_length=50, verbose_name='Страна')),
                ('wins', models.IntegerField(verbose_name='Количество подеб')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания статьи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='season.teams', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Гонщики',
                'verbose_name_plural': 'Гонщики',
                'ordering': ['name', 'time_create'],
            },
        ),
    ]
