# Generated by Django 4.0.3 on 2022-04-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_teams_drivers_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivers',
            options={'ordering': ['name', 'time_create'], 'verbose_name': 'Гонщики', 'verbose_name_plural': 'Гонщики'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Команды', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='drivers',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='fromCountry',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='season.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания статьи'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='wins',
            field=models.IntegerField(verbose_name='Количество подеб'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Команда'),
        ),
    ]
